// UI dictionaries. en + ru are complete; de/fr/es cover the shell and fall back to en.
// Copy rule: say what the person does or gets, in their words. No internal jargon.

export const en = {
  "app.tagline": "The apprentice that learns the why.",

  "nav.home": "Home",
  "nav.learn": "Walk me through",
  "nav.workflows": "Workflows",
  "nav.skip": "Skip to content",
  "nav.menu": "Menu",
  "nav.primary": "Main",
  "nav.inbox": "Requests",
  "nav.map": "Work Map",

  "role.label": "Viewing as",
  "role.learner": "Learner",
  "role.expert": "Expert",
  "role.learner.sub": "Learn workflows on your own screen",
  "role.expert.sub": "Teach Claros, answer learners",
  "role.switch": "Switch role",

  "lang.label": "Language",
  "theme.label": "Theme",
  "theme.system": "System",
  "theme.light": "Light",
  "theme.dark": "Dark",

  "crumb.home": "Home",
  "crumb.learn": "Walk me through",
  "crumb.workflows": "Workflows",
  "focus.capture": "Recording",
  "focus.debrief": "Debrief",
  "focus.exit": "Exit",

  "data.demo": "Demo data",
  "data.demo.hint": "Claros server not reachable — showing demo data",
  "data.live": "Live",

  "common.open": "Open",
  "common.later": "Later",
  "common.close": "Close",
  "common.prev": "Previous step",
  "common.next": "Next step",
  "common.undo": "Undo",
  "common.all": "All",
  "common.steps": "{n} steps",

  "cov.ready": "Ready",
  "cov.partial": "Partial",
  "cov.missing": "Missing",
  "cov.ready.long": "Confirmed by experts",
  "cov.partial.long": "Some parts not confirmed yet",
  "cov.missing.long": "Nobody has shown Claros this yet",

  "state.loading": "Loading…",
  "state.error.title": "Couldn't load this",
  "state.error.sub": "Check your connection, then try again.",
  "state.error.retry": "Try again",
  "state.empty.workflows": "No workflows yet. The first one appears after an expert records one.",
  "state.empty.requests": "No open requests.",
  "state.empty.contrib": "You haven't taught Claros anything yet.",

  /* expert home */
  "home.expert.title": "Where your know-how is needed",
  "home.expert.sub": "Claros only spends your time where a learner is actually stuck, or where it can't find the answer anywhere else.",
  "home.requests.title": "Requests from learners",
  "home.requests.sub": "Each is a person stuck on a real screen. Recording starts from their moment.",
  "home.requests.empty": "No one is waiting on you. When a learner hits something Claros hasn't been shown, it lands here.",
  "req.trying": "Trying to",
  "req.by": "{name} · {ago}",
  "req.record": "Record it now",
  "req.later": "Later",
  "req.snoozed": "Moved to later",
  "req.laterList": "Saved for later ({n})",
  "req.moment": "Their screen when they got stuck",
  "req.status.accepted": "You're on it",
  "req.status.recorded": "Recorded",
  "req.status.done": "Published",
  "home.questions.title": "Questions waiting for you",
  "home.questions.sub": "Only what Claros couldn't find in docs or general knowledge. Answer out loud — about a minute each.",
  "home.questions.empty": "Nothing open. Claros asks here when a learner hits a case your map doesn't cover, or when experts disagree.",
  "q.kind.conflict": "Experts differ",
  "q.kind.coverage": "New case from a learner",
  "q.kind.why": "Why",
  "q.kind.limit": "Where's the line",
  "q.kind.stop_and_ask": "When to stop",
  "q.kind.never": "Never do",
  "q.kind.deliberate": "On purpose?",
  "q.answer": "Answer by voice",
  "q.in": "In “{name}”",
  "q.see": "See on map",
  "q.conflict.at": "At “{step}”",
  "home.workflows.title": "Your workflows",
  "home.workflows.team": "Workflows on your team",
  "home.workflows.empty": "You haven't taught Claros anything yet.",
  "home.teach.title": "Teach Claros something new",
  "home.teach.sub": "Work as usual and talk it through. Claros asks only at pauses.",
  "home.teach.cta": "Start recording",

  "wf.evidence": "Evidence",
  "wf.judgments": "Decisions",
  "wf.guardrails": "Rules",
  "wf.open": "Open questions: {n}",
  "wf.conflicts": "Disagreements: {n}",
  "wf.experts": "{n} experts",
  "wf.updated": "Updated {ago}",
  "wf.learn": "Learn this",
  "wf.view": "View map",

  /* learner home */
  "home.learner.title": "Stuck on a screen?",
  "home.learner.sub": "Share the window you're working in. Claros finds the workflow and walks you through it on your own case.",
  "home.learner.cta": "Walk me through this",
  "home.learner.hint": "or say “Claros, walk me through this”",
  "home.continue.title": "Continue learning",
  "home.continue.empty": "Nothing started yet. Pick a workflow below, or let Claros walk you through your screen.",
  "mastery.progress": "{done} of {total} steps on your own",
  "mastery.practice": "Practice next",
  "mastery.next": "Next up: {step}",
  "home.library.title": "Workflows you can learn",
  "home.library.empty": "No workflows yet. The first one appears after an expert records one.",
  "home.library.none": "Nothing matches this filter.",
  "home.library.app": "App",
  "home.library.coverage": "Coverage",
  "home.myreq.title": "Your requests",
  "home.myreq.empty": "When Claros doesn't know something yet, ask an expert. Your requests show up here.",
  "myreq.asked": "Asked",
  "myreq.recorded": "Recorded",
  "myreq.ready": "Ready",
  "myreq.start": "Start learning",

  /* library page */
  "lib.title": "Workflows",
  "lib.sub": "Everything experts have shown Claros. Coverage tells you how much of it is confirmed.",

  /* debug */
  "debug.title": "Demo controls",
  "debug.force": "Force coverage on lookup",
  "debug.auto": "Auto",
  "debug.hint": "Only visible with ?debug=1",

  /* learn */
  "learn.invoke.title": "Walk me through this",
  "learn.invoke.sub": "Claros looks at the window you share and listens to what you're trying to do. Nothing is recorded until you start.",
  "learn.invoke.share": "Share my window",
  "learn.invoke.voice": "Talk to Claros",
  "learn.invoke.voiceOn": "Listening",
  "learn.invoke.intent": "What are you trying to do?",
  "learn.invoke.intent.ph": "e.g. finish this form the way my team does",
  "learn.invoke.preview": "Your shared window appears here",
  "learn.invoke.demo": "Demo: force coverage",
  "learn.sharing": "Sharing",
  "learn.lookup": "Finding this workflow…",
  "learn.lookup.sub": "Matching your screen and words against what experts have shown Claros",
  "learn.ready.title": "I know this one.",
  "learn.ready.sub": "Confirmed by {experts}. Let's do it on your case — predict before I tell you.",
  "learn.partial.title": "I know part of this.",
  "learn.partial.sub": "I'll teach what experts confirmed. Where nobody has confirmed it yet, I'll say so instead of guessing.",
  "learn.missing.title": "Nobody has shown me this yet.",
  "learn.missing.sub": "I won't guess at your company's rules. I can ask an expert — they'll see exactly the screen you're on.",
  "learn.missing.ask": "Ask an expert",
  "learn.missing.asked": "Request sent",
  "learn.missing.asked.sub": "{name} will see your screen moment. You'll find it under “Your requests” on Home.",
  "learn.missing.home": "Back to Home",
  "learn.missing.onet": "Looks like this task",
  "learn.start": "Start",
  "learn.step": "Step {n} of {total}",
  "learn.predict.q": "What would you do here?",
  "learn.predict.voice": "Answer by voice",
  "learn.predict.reveal": "Show me",
  "learn.predict.correct": "That's what the expert does.",
  "learn.predict.wrong": "Not quite — here's why.",
  "learn.notConfirmed": "Not confirmed yet",
  "learn.notConfirmed.sub": "No expert has confirmed this step. Ask your lead before acting.",
  "learn.intervene.title": "{name} would stop here.",
  "learn.intervene.ask": "Why do you think?",
  "learn.intervene.ack": "Got it — continue",
  "learn.intervene.flip": "What {name} saw",
  "learn.next": "Next step",
  "learn.mastery.title": "Your run",
  "learn.mastery.sub": "“On your own” means you predicted it right without help.",
  "learn.mastery.practice": "Practice next",
  "learn.mastery.practice.sub": "Your weakest step, on a fresh case",
  "learn.lvl.unseen": "Not yet",
  "learn.lvl.caught": "Caught",
  "learn.lvl.hinted": "With a hint",
  "learn.lvl.unaided": "On your own",
  "learn.conflict.title": "Experts differ here",
  "learn.conflict.ask": "Ask your lead before you choose.",
  "learn.end": "Start over",
  "learn.steps": "Steps",

  "quote.original": "Original",
  "quote.play": "Play the expert's voice",
  "quote.pause": "Pause",
  "quote.translation": "Translation",
  "quote.src.live": "said while working",
  "quote.src.debrief": "said in debrief",
  "quote.src.doc": "from a document",
  "quote.src.inbox": "answered later",

  /* capture */
  "capture.preflight.title": "Before Claros watches",
  "capture.preflight.sub": "Just work and talk. Claros asks at most a few questions, only at pauses.",
  "capture.preflight.mic": "Microphone",
  "capture.preflight.mic.ok": "Microphone ready",
  "capture.preflight.mic.test": "Test microphone",
  "capture.preflight.mic.denied": "Microphone blocked — allow it from the browser's address bar.",
  "capture.voice": "Voice",
  "capture.preflight.window": "Share one window, not your whole screen",
  "capture.preflight.window.sub": "Pick the app window you work in. Other windows, notifications and tabs stay private.",
  "capture.preflight.monitor": "That's your whole screen. Share a single window instead.",
  "capture.preflight.captured": "Captured",
  "capture.preflight.captured.list": "Snapshots of the shared window (sensitive fields masked)|What you say while on the record|Field changes Claros sees on screen",
  "capture.preflight.never": "Never captured",
  "capture.preflight.never.list": "Other windows or tabs|Anything said off the record|Raw video or your face|Passwords and masked fields",
  "capture.preflight.lang": "I'll speak",
  "capture.preflight.consent": "I understand what's captured and agree to start.",
  "capture.preflight.start": "Start recording",
  "capture.notebook": "Apprentice's notebook",
  "capture.events": "What Claros saw",
  "capture.asked": "Asked you",
  "capture.saved": "Saved for debrief",
  "capture.saved.sub": "Claros is holding these so you can keep working.",
  "capture.budget": "Question budget",
  "capture.budget.sub": "{used} of {max} in 10 min",
  "capture.why": "Why Claros asked",
  "capture.why.scope": "Kind of knowledge",
  "capture.why.hypothesis": "Its guess",
  "capture.why.priority": "Priority",
  "capture.why.gate": "Timing",
  "capture.why.gate.pause": "You paused for {s}s — a safe moment",
  "capture.why.gate.resolved": "Answered from {source} — not asked",
  "capture.why.gate.deferred": "Saved: you were busy",
  "capture.why.none": "Pick a question to see why Claros asked it.",
  "capture.offrecord": "Off the record",
  "capture.offrecord.on": "Off the record — nothing is captured",
  "capture.offrecord.resume": "Back on the record",
  "capture.end": "End & debrief",
  "capture.live": "On the record",
  "capture.empty.events": "Work as usual. What Claros notices on screen appears here.",

  /* debrief */
  "debrief.title": "Debrief",
  "debrief.stop": "Stop here",
  "debrief.ledger": "Open questions",
  "debrief.ledger.budget": "Up to 6 questions · about 5 min",
  "debrief.ledger.done": "Nothing left to ask. Thank you.",
  "debrief.moment": "This moment",
  "debrief.question": "Claros asks",
  "debrief.answer.voice": "Answer by voice",
  "debrief.answer.type": "Type an answer",
  "debrief.answer.skip": "Not relevant",
  "debrief.answer.submit": "Save answer",
  "debrief.map": "Map so far",
  "debrief.teachback": "Teach-back",
  "debrief.teachback.sub": "Claros explains the workflow back. Stop it the moment it's wrong.",
  "debrief.teachback.play": "Play teach-back",
  "debrief.correction": "Your corrections",
  "debrief.correction.empty": "Stop the teach-back where it's wrong — your fixes collect here.",
  "debrief.correction.ph": "What should it say instead?",
  "debrief.correction.save": "Save fix",
  "debrief.exam": "Unseen cases",
  "debrief.exam.sub": "Claros predicts what you'd do on cases it hasn't seen. Mark each one.",
  "debrief.exam.predicts": "Claros would",
  "debrief.exam.confidence": "sure",
  "debrief.exam.right": "Right",
  "debrief.exam.wrong": "Wrong",
  "debrief.exam.empty": "No unseen cases for this workflow yet.",
  "debrief.publish": "Publish map",
  "debrief.publish.sub": "Learners will be taught exactly what you confirmed.",
  "debrief.publish.blocked": "Mark every case first",
  "debrief.published": "Published",

  /* work map */
  "map.learnThis": "Learn this",
  "map.export": "Export",
  "map.export.skill": "SKILL.md for agents",
  "map.export.mcp": "Copy MCP URL",
  "map.export.json": "Raw JSON",
  "map.copied": "MCP URL copied",
  "map.version": "v{n}",
  "map.experts": "Experts",
  "map.task": "O*NET task",
  "map.coverage": "Coverage",
  "map.evidence": "Steps with evidence",
  "map.judgments": "Decisions explained",
  "map.guardrails": "Rules confirmed",
  "map.filter.label": "Show",
  "map.filter.all": "All",
  "map.filter.judgment": "Judgment calls",
  "map.filter.guardrail": "Guardrails",
  "map.filter.conflict": "Conflicts",
  "map.filter.unconfirmed": "Unconfirmed",
  "map.filter.empty": "No steps match this filter.",
  "map.anyOrder": "Any order",
  "map.anyOrder.sub": "These can happen in either order.",
  "map.step": "Step {n}",
  "map.open": "Open",
  "map.frames": "{n} frames",
  "map.minimap": "Steps at a glance",
  "map.minimap.show": "Show mini-map",
  "map.minimap.hide": "Hide mini-map",
  "chip.judgment": "Judgment call",
  "chip.guardrail": "Guardrail",
  "chip.conflict": "Experts differ",
  "chip.unconfirmed": "Not confirmed",
  "chip.notes": "{n} background",
  "legend.title": "How to read this",
  "legend.judgment": "An expert decides based on the case",
  "legend.guardrail": "A hard rule: stop, hold or ask",
  "legend.conflict": "Experts do this differently",
  "legend.unconfirmed": "No expert has confirmed it yet",
  "legend.anyOrder": "Steps that can happen in either order",
  "map.conflictBanner": "Experts differ at step {n}",
  "map.conflictBanner.cta": "See both reasons",
  "map.screen": "What the expert saw",
  "map.decision": "Decision",
  "map.reason": "Why",
  "map.rules": "Guardrails",
  "map.context": "Background",
  "map.counterfactual": "Would change if",
  "map.variants": "How each expert does it",
  "map.conflict": "Experts differ here",
  "map.approve": "Approved",
  "map.owner": "Ask",
  "map.unconfirmed": "Not confirmed yet",
  "map.unconfirmed.sub": "No expert has confirmed this step. Learners see it marked, never as a rule.",
  "map.notFound": "This map doesn't exist yet.",
  "map.openq.title": "Open questions",
  "map.openq.sub": "Claros will ask an expert about these before teaching them.",
  "map.nothingMore": "That's everything Claros knows about this step.",

  "guard.block_and_explain": "Blocks",
  "guard.warn": "Warns",
  "guard.stop_and_ask": "Stop & ask",
  "guard.hold": "Hold",

  "scope.universal": "General knowledge",
  "scope.app": "App docs",
  "scope.occupation": "O*NET",
  "scope.company": "Company rule",
  "scope.personal_judgment": "Personal judgment",

  "time.justNow": "just now",
  "time.min": "{n} min ago",
  "time.hour": "{n} h ago",
  "time.day": "{n} d ago",
};

export type DictKey = keyof typeof en;
export type Dict = Partial<Record<DictKey, string>>;

export const ru: Record<DictKey, string> = {
  "app.tagline": "Ученик, который понимает «почему».",

  "nav.home": "Главная",
  "nav.learn": "Проведи меня",
  "nav.workflows": "Процессы",
  "nav.skip": "К содержимому",
  "nav.menu": "Меню",
  "nav.primary": "Основное",
  "nav.inbox": "Запросы",
  "nav.map": "Карта работы",

  "role.label": "Смотрю как",
  "role.learner": "Новичок",
  "role.expert": "Эксперт",
  "role.learner.sub": "Учусь процессам на своём экране",
  "role.expert.sub": "Учу Claros, отвечаю новичкам",
  "role.switch": "Сменить роль",

  "lang.label": "Язык",
  "theme.label": "Тема",
  "theme.system": "Как в системе",
  "theme.light": "Светлая",
  "theme.dark": "Тёмная",

  "crumb.home": "Главная",
  "crumb.learn": "Проведи меня",
  "crumb.workflows": "Процессы",
  "focus.capture": "Запись",
  "focus.debrief": "Разбор",
  "focus.exit": "Выйти",

  "data.demo": "Демо-данные",
  "data.demo.hint": "Сервер Claros недоступен — показаны демо-данные",
  "data.live": "Онлайн",

  "common.open": "Открыть",
  "common.later": "Позже",
  "common.close": "Закрыть",
  "common.prev": "Предыдущий шаг",
  "common.next": "Следующий шаг",
  "common.undo": "Отменить",
  "common.all": "Все",
  "common.steps": "Шагов: {n}",

  "cov.ready": "Готово",
  "cov.partial": "Частично",
  "cov.missing": "Нет",
  "cov.ready.long": "Подтверждено экспертами",
  "cov.partial.long": "Часть ещё не подтверждена",
  "cov.missing.long": "Этому Claros ещё никто не показывал",

  "state.loading": "Загрузка…",
  "state.error.title": "Не удалось загрузить",
  "state.error.sub": "Проверьте соединение и попробуйте ещё раз.",
  "state.error.retry": "Повторить",
  "state.empty.workflows": "Пока нет процессов. Первый появится после записи эксперта.",
  "state.empty.requests": "Открытых запросов нет.",
  "state.empty.contrib": "Вы ещё ничему не научили Claros.",

  "home.expert.title": "Где нужен ваш опыт",
  "home.expert.sub": "Claros тратит ваше время только там, где новичок действительно застрял или где ответа больше нигде нет.",
  "home.requests.title": "Запросы от новичков",
  "home.requests.sub": "За каждым — человек, застрявший на реальном экране. Запись начнётся с его момента.",
  "home.requests.empty": "Вас никто не ждёт. Когда новичок упрётся в то, чего Claros не показывали, запрос придёт сюда.",
  "req.trying": "Хотел(а)",
  "req.by": "{name} · {ago}",
  "req.record": "Записать сейчас",
  "req.later": "Позже",
  "req.snoozed": "Отложено",
  "req.laterList": "Отложено ({n})",
  "req.moment": "Их экран в момент затруднения",
  "req.status.accepted": "Вы взялись",
  "req.status.recorded": "Записано",
  "req.status.done": "Опубликовано",
  "home.questions.title": "Вопросы к вам",
  "home.questions.sub": "Только то, чего Claros не нашёл в документации и общих знаниях. Ответьте вслух — около минуты на вопрос.",
  "home.questions.empty": "Открытых вопросов нет. Claros спросит здесь, когда новичок столкнётся со случаем вне карты или когда эксперты разойдутся.",
  "q.kind.conflict": "Эксперты расходятся",
  "q.kind.coverage": "Новый случай от новичка",
  "q.kind.why": "Почему",
  "q.kind.limit": "Где граница",
  "q.kind.stop_and_ask": "Когда остановиться",
  "q.kind.never": "Никогда",
  "q.kind.deliberate": "Намеренно?",
  "q.answer": "Ответить голосом",
  "q.in": "В «{name}»",
  "q.see": "Показать на карте",
  "q.conflict.at": "На шаге «{step}»",
  "home.workflows.title": "Ваши процессы",
  "home.workflows.team": "Процессы команды",
  "home.workflows.empty": "Вы ещё ничему не научили Claros.",
  "home.teach.title": "Научить Claros новому",
  "home.teach.sub": "Работайте как обычно и проговаривайте. Claros спрашивает только в паузах.",
  "home.teach.cta": "Начать запись",

  "wf.evidence": "Доказательства",
  "wf.judgments": "Решения",
  "wf.guardrails": "Правила",
  "wf.open": "Открытых вопросов: {n}",
  "wf.conflicts": "Расхождений: {n}",
  "wf.experts": "Экспертов: {n}",
  "wf.updated": "Обновлено {ago}",
  "wf.learn": "Учиться",
  "wf.view": "Открыть карту",

  "home.learner.title": "Застряли на экране?",
  "home.learner.sub": "Покажите окно, в котором работаете. Claros найдёт процесс и проведёт вас по нему на вашем же случае.",
  "home.learner.cta": "Проведи меня",
  "home.learner.hint": "или скажите «Claros, проведи меня»",
  "home.continue.title": "Продолжить обучение",
  "home.continue.empty": "Пока ничего не начато. Выберите процесс ниже или попросите Claros провести вас по вашему экрану.",
  "mastery.progress": "Сами: {done} из {total} шагов",
  "mastery.practice": "Потренироваться",
  "mastery.next": "Дальше: {step}",
  "home.library.title": "Процессы, которым можно научиться",
  "home.library.empty": "Пока нет процессов. Первый появится после записи эксперта.",
  "home.library.none": "Под этот фильтр ничего не подходит.",
  "home.library.app": "Приложение",
  "home.library.coverage": "Покрытие",
  "home.myreq.title": "Ваши запросы",
  "home.myreq.empty": "Когда Claros чего-то не знает, спросите эксперта. Ваши запросы появятся здесь.",
  "myreq.asked": "Спросили",
  "myreq.recorded": "Записано",
  "myreq.ready": "Готово",
  "myreq.start": "Начать обучение",

  "lib.title": "Процессы",
  "lib.sub": "Всё, что эксперты показали Claros. Покрытие показывает, какая часть подтверждена.",

  "debug.title": "Демо-настройки",
  "debug.force": "Покрытие при поиске",
  "debug.auto": "Авто",
  "debug.hint": "Видно только с ?debug=1",

  "learn.invoke.title": "Проведи меня",
  "learn.invoke.sub": "Claros смотрит на окно, которым вы поделились, и слушает, что вы хотите сделать. Ничего не записывается, пока вы не начнёте.",
  "learn.invoke.share": "Показать окно",
  "learn.invoke.voice": "Говорить с Claros",
  "learn.invoke.voiceOn": "Слушаю",
  "learn.invoke.intent": "Что вы хотите сделать?",
  "learn.invoke.intent.ph": "напр. заполнить эту форму так, как принято у нас",
  "learn.invoke.preview": "Здесь появится окно, которым вы поделитесь",
  "learn.invoke.demo": "Демо: покрытие",
  "learn.sharing": "Показ",
  "learn.lookup": "Ищу этот процесс…",
  "learn.lookup.sub": "Сравниваю ваш экран и слова с тем, что эксперты показали Claros",
  "learn.ready.title": "Это я знаю.",
  "learn.ready.sub": "Подтверждено: {experts}. Сделаем на вашем случае — сначала предскажите, потом я подскажу.",
  "learn.partial.title": "Это я знаю частично.",
  "learn.partial.sub": "Научу тому, что подтвердили эксперты. Где подтверждения нет — так и скажу, а не буду гадать.",
  "learn.missing.title": "Мне это ещё никто не показывал.",
  "learn.missing.sub": "Я не буду угадывать правила вашей компании. Могу спросить эксперта — он увидит ровно тот экран, на котором вы сейчас.",
  "learn.missing.ask": "Спросить эксперта",
  "learn.missing.asked": "Запрос отправлен",
  "learn.missing.asked.sub": "{name} увидит ваш момент на экране. Запрос будет в разделе «Ваши запросы» на главной.",
  "learn.missing.home": "На главную",
  "learn.missing.onet": "Похоже на задачу",
  "learn.start": "Начать",
  "learn.step": "Шаг {n} из {total}",
  "learn.predict.q": "Что бы вы сделали здесь?",
  "learn.predict.voice": "Ответить голосом",
  "learn.predict.reveal": "Покажи",
  "learn.predict.correct": "Именно так делает эксперт.",
  "learn.predict.wrong": "Не совсем — вот почему.",
  "learn.notConfirmed": "Ещё не подтверждено",
  "learn.notConfirmed.sub": "Этот шаг не подтвердил ни один эксперт. Спросите руководителя, прежде чем действовать.",
  "learn.intervene.title": "{name} остановилась бы здесь.",
  "learn.intervene.ask": "Как думаете, почему?",
  "learn.intervene.ack": "Понятно — дальше",
  "learn.intervene.flip": "Что видел(а) {name}",
  "learn.next": "Следующий шаг",
  "learn.mastery.title": "Ваш проход",
  "learn.mastery.sub": "«Сами» — вы предсказали верно без подсказки.",
  "learn.mastery.practice": "Потренироваться",
  "learn.mastery.practice.sub": "Самый слабый шаг — на новом случае",
  "learn.lvl.unseen": "Ещё нет",
  "learn.lvl.caught": "Поймали",
  "learn.lvl.hinted": "С подсказкой",
  "learn.lvl.unaided": "Сами",
  "learn.conflict.title": "Эксперты расходятся",
  "learn.conflict.ask": "Спросите руководителя, прежде чем выбрать.",
  "learn.end": "Начать заново",
  "learn.steps": "Шаги",

  "quote.original": "Оригинал",
  "quote.play": "Послушать эксперта",
  "quote.pause": "Пауза",
  "quote.translation": "Перевод",
  "quote.src.live": "сказано во время работы",
  "quote.src.debrief": "сказано на разборе",
  "quote.src.doc": "из документа",
  "quote.src.inbox": "ответ позже",

  "capture.preflight.title": "Прежде чем Claros начнёт смотреть",
  "capture.preflight.sub": "Просто работайте и рассказывайте. Claros задаст максимум несколько вопросов и только в паузах.",
  "capture.preflight.mic": "Микрофон",
  "capture.preflight.mic.ok": "Микрофон готов",
  "capture.preflight.mic.test": "Проверить микрофон",
  "capture.preflight.mic.denied": "Микрофон заблокирован — разрешите доступ в адресной строке браузера.",
  "capture.voice": "Голос",
  "capture.preflight.window": "Покажите одно окно, а не весь экран",
  "capture.preflight.window.sub": "Выберите окно приложения, в котором работаете. Другие окна, уведомления и вкладки остаются приватными.",
  "capture.preflight.monitor": "Это весь экран. Лучше покажите одно окно.",
  "capture.preflight.captured": "Записывается",
  "capture.preflight.captured.list": "Снимки показанного окна (чувствительные поля скрыты)|Что вы говорите под запись|Изменения полей, которые Claros видит на экране",
  "capture.preflight.never": "Никогда не записывается",
  "capture.preflight.never.list": "Другие окна и вкладки|Всё сказанное не под запись|Видео целиком и ваше лицо|Пароли и скрытые поля",
  "capture.preflight.lang": "Я буду говорить на",
  "capture.preflight.consent": "Я понимаю, что записывается, и согласен(на) начать.",
  "capture.preflight.start": "Начать запись",
  "capture.notebook": "Тетрадь ученика",
  "capture.events": "Что увидел Claros",
  "capture.asked": "Спросил вас",
  "capture.saved": "Отложено на разбор",
  "capture.saved.sub": "Claros придержал эти вопросы, чтобы вы могли работать.",
  "capture.budget": "Лимит вопросов",
  "capture.budget.sub": "{used} из {max} за 10 мин",
  "capture.why": "Почему Claros спросил",
  "capture.why.scope": "Тип знания",
  "capture.why.hypothesis": "Его догадка",
  "capture.why.priority": "Приоритет",
  "capture.why.gate": "Момент",
  "capture.why.gate.pause": "Пауза {s} с — удобный момент",
  "capture.why.gate.resolved": "Ответ найден: {source} — не спрашивал",
  "capture.why.gate.deferred": "Отложено: вы были заняты",
  "capture.why.none": "Выберите вопрос, чтобы увидеть, почему Claros его задал.",
  "capture.offrecord": "Не под запись",
  "capture.offrecord.on": "Не под запись — ничего не сохраняется",
  "capture.offrecord.resume": "Снова под запись",
  "capture.end": "Завершить и разобрать",
  "capture.live": "Идёт запись",
  "capture.empty.events": "Работайте как обычно. Всё, что Claros заметит на экране, появится здесь.",

  "debrief.title": "Разбор",
  "debrief.stop": "Стоп",
  "debrief.ledger": "Открытые вопросы",
  "debrief.ledger.budget": "До 6 вопросов · около 5 мин",
  "debrief.ledger.done": "Вопросов больше нет. Спасибо.",
  "debrief.moment": "Этот момент",
  "debrief.question": "Claros спрашивает",
  "debrief.answer.voice": "Ответить голосом",
  "debrief.answer.type": "Написать ответ",
  "debrief.answer.skip": "Неважно",
  "debrief.answer.submit": "Сохранить ответ",
  "debrief.map": "Карта на сейчас",
  "debrief.teachback": "Пересказ",
  "debrief.teachback.sub": "Claros пересказывает процесс. Остановите его, как только он ошибётся.",
  "debrief.teachback.play": "Запустить пересказ",
  "debrief.correction": "Ваши исправления",
  "debrief.correction.empty": "Остановите пересказ там, где он неверен, — исправления соберутся здесь.",
  "debrief.correction.ph": "Как должно быть?",
  "debrief.correction.save": "Сохранить",
  "debrief.exam": "Новые случаи",
  "debrief.exam.sub": "Claros предсказывает, что бы вы сделали в случаях, которых он не видел. Отметьте каждый.",
  "debrief.exam.predicts": "Claros сделал бы",
  "debrief.exam.confidence": "уверенность",
  "debrief.exam.right": "Верно",
  "debrief.exam.wrong": "Неверно",
  "debrief.exam.empty": "Для этого процесса пока нет новых случаев.",
  "debrief.publish": "Опубликовать карту",
  "debrief.publish.sub": "Новички будут учиться ровно тому, что вы подтвердили.",
  "debrief.publish.blocked": "Сначала отметьте все случаи",
  "debrief.published": "Опубликовано",

  "map.learnThis": "Учиться",
  "map.export": "Экспорт",
  "map.export.skill": "SKILL.md для агентов",
  "map.export.mcp": "Скопировать MCP URL",
  "map.export.json": "JSON",
  "map.copied": "MCP URL скопирован",
  "map.version": "в{n}",
  "map.experts": "Эксперты",
  "map.task": "Задача O*NET",
  "map.coverage": "Покрытие",
  "map.evidence": "Шаги с доказательствами",
  "map.judgments": "Решения объяснены",
  "map.guardrails": "Правила подтверждены",
  "map.filter.label": "Показать",
  "map.filter.all": "Все",
  "map.filter.judgment": "Решения",
  "map.filter.guardrail": "Ограничения",
  "map.filter.conflict": "Расхождения",
  "map.filter.unconfirmed": "Не подтверждено",
  "map.filter.empty": "Под этот фильтр шагов нет.",
  "map.anyOrder": "В любом порядке",
  "map.anyOrder.sub": "Эти шаги можно делать в любом порядке.",
  "map.step": "Шаг {n}",
  "map.open": "Открыть",
  "map.frames": "Кадров: {n}",
  "map.minimap": "Шаги кратко",
  "map.minimap.show": "Показать мини-карту",
  "map.minimap.hide": "Скрыть мини-карту",
  "chip.judgment": "Решение",
  "chip.guardrail": "Ограничение",
  "chip.conflict": "Расхождение",
  "chip.unconfirmed": "Не подтверждено",
  "chip.notes": "Контекст: {n}",
  "legend.title": "Как читать карту",
  "legend.judgment": "Эксперт решает по ситуации",
  "legend.guardrail": "Жёсткое правило: стоп, удержать или спросить",
  "legend.conflict": "Эксперты делают по-разному",
  "legend.unconfirmed": "Ни один эксперт ещё не подтвердил",
  "legend.anyOrder": "Шаги, которые можно делать в любом порядке",
  "map.conflictBanner": "Эксперты расходятся на шаге {n}",
  "map.conflictBanner.cta": "Посмотреть обе причины",
  "map.screen": "Что видел эксперт",
  "map.decision": "Решение",
  "map.reason": "Почему",
  "map.rules": "Ограничения",
  "map.context": "Контекст",
  "map.counterfactual": "Изменится, если",
  "map.variants": "Как делает каждый эксперт",
  "map.conflict": "Эксперты расходятся",
  "map.approve": "Утверждено",
  "map.owner": "Спросить",
  "map.unconfirmed": "Ещё не подтверждено",
  "map.unconfirmed.sub": "Этот шаг не подтвердил ни один эксперт. Новички видят его с пометкой, а не как правило.",
  "map.notFound": "Такой карты пока нет.",
  "map.openq.title": "Открытые вопросы",
  "map.openq.sub": "Claros спросит об этом эксперта, прежде чем учить.",
  "map.nothingMore": "Это всё, что Claros знает об этом шаге.",

  "guard.block_and_explain": "Блокирует",
  "guard.warn": "Предупреждает",
  "guard.stop_and_ask": "Стоп и спросить",
  "guard.hold": "Удержать",

  "scope.universal": "Общее знание",
  "scope.app": "Документация",
  "scope.occupation": "O*NET",
  "scope.company": "Правило компании",
  "scope.personal_judgment": "Личное суждение",

  "time.justNow": "только что",
  "time.min": "{n} мин назад",
  "time.hour": "{n} ч назад",
  "time.day": "{n} дн назад",
};

export const de: Dict = {
  "nav.home": "Start", "nav.learn": "Zeig's mir", "nav.workflows": "Abläufe", "nav.skip": "Zum Inhalt", "nav.menu": "Menü", "nav.primary": "Hauptmenü",
  "role.label": "Ansicht als", "role.learner": "Lernende:r", "role.expert": "Expert:in", "role.learner.sub": "Abläufe am eigenen Bildschirm lernen", "role.expert.sub": "Claros etwas beibringen, Fragen beantworten", "role.switch": "Rolle wechseln",
  "lang.label": "Sprache", "theme.label": "Design", "theme.system": "System", "theme.light": "Hell", "theme.dark": "Dunkel",
  "crumb.home": "Start", "crumb.learn": "Zeig's mir", "crumb.workflows": "Abläufe", "focus.capture": "Aufnahme", "focus.debrief": "Nachbesprechung", "focus.exit": "Beenden",
  "data.demo": "Demodaten", "data.demo.hint": "Claros-Server nicht erreichbar — Demodaten",
  "common.open": "Öffnen", "common.later": "Später", "common.close": "Schließen", "common.prev": "Vorheriger Schritt", "common.next": "Nächster Schritt", "common.undo": "Rückgängig", "common.all": "Alle",
  "cov.ready": "Bereit", "cov.partial": "Teilweise", "cov.missing": "Fehlt",
  "state.loading": "Lädt…", "state.error.title": "Konnte nicht geladen werden", "state.error.retry": "Erneut versuchen",
  "home.expert.title": "Wo dein Wissen gebraucht wird", "home.requests.title": "Anfragen von Lernenden", "req.record": "Jetzt aufnehmen", "req.later": "Später",
  "home.questions.title": "Fragen an dich", "q.answer": "Per Sprache antworten", "home.workflows.title": "Deine Abläufe", "home.teach.title": "Claros etwas Neues beibringen", "home.teach.cta": "Aufnahme starten",
  "home.learner.title": "Hängst du an einem Bildschirm fest?", "home.learner.cta": "Zeig mir, wie das geht", "home.continue.title": "Weiterlernen", "home.library.title": "Abläufe zum Lernen", "home.myreq.title": "Deine Anfragen",
  "wf.learn": "Lernen", "wf.view": "Karte ansehen",
  "learn.missing.title": "Das hat mir noch niemand gezeigt.", "learn.missing.ask": "Eine Expertin fragen",
  "learn.intervene.title": "{name} würde hier anhalten.", "learn.intervene.ask": "Was glaubst du, warum?",
  "learn.notConfirmed": "Noch nicht bestätigt", "map.conflict": "Hier sind sich die Expert:innen uneinig",
  "capture.offrecord": "Inoffiziell", "debrief.publish": "Karte veröffentlichen",
  "map.filter.all": "Alle", "map.filter.judgment": "Ermessensfragen", "map.filter.guardrail": "Leitplanken", "map.filter.conflict": "Konflikte", "map.filter.unconfirmed": "Unbestätigt",
  "chip.judgment": "Ermessen", "chip.guardrail": "Leitplanke", "chip.conflict": "Uneinig", "chip.unconfirmed": "Unbestätigt", "map.anyOrder": "Beliebige Reihenfolge", "map.open": "Öffnen", "map.export": "Export", "map.learnThis": "Das lernen",
};

export const fr: Dict = {
  "nav.home": "Accueil", "nav.learn": "Guide-moi", "nav.workflows": "Processus", "nav.skip": "Aller au contenu", "nav.menu": "Menu", "nav.primary": "Principal",
  "role.label": "Vue", "role.learner": "Apprenant·e", "role.expert": "Expert·e", "role.learner.sub": "Apprendre sur son propre écran", "role.expert.sub": "Former Claros, répondre aux apprenants", "role.switch": "Changer de rôle",
  "lang.label": "Langue", "theme.label": "Thème", "theme.system": "Système", "theme.light": "Clair", "theme.dark": "Sombre",
  "crumb.home": "Accueil", "crumb.learn": "Guide-moi", "crumb.workflows": "Processus", "focus.capture": "Enregistrement", "focus.debrief": "Débrief", "focus.exit": "Quitter",
  "data.demo": "Données démo", "data.demo.hint": "Serveur Claros injoignable — données démo",
  "common.open": "Ouvrir", "common.later": "Plus tard", "common.close": "Fermer", "common.prev": "Étape précédente", "common.next": "Étape suivante", "common.undo": "Annuler", "common.all": "Tous",
  "cov.ready": "Prêt", "cov.partial": "Partiel", "cov.missing": "Manquant",
  "state.loading": "Chargement…", "state.error.title": "Chargement impossible", "state.error.retry": "Réessayer",
  "home.expert.title": "Là où votre savoir-faire compte", "home.requests.title": "Demandes des apprenants", "req.record": "Enregistrer maintenant", "req.later": "Plus tard",
  "home.questions.title": "Questions pour vous", "q.answer": "Répondre à voix haute", "home.workflows.title": "Vos processus", "home.teach.title": "Apprendre quelque chose à Claros", "home.teach.cta": "Commencer l'enregistrement",
  "home.learner.title": "Bloqué·e sur un écran ?", "home.learner.cta": "Guide-moi", "home.continue.title": "Continuer", "home.library.title": "Processus à apprendre", "home.myreq.title": "Vos demandes",
  "wf.learn": "Apprendre", "wf.view": "Voir la carte",
  "learn.missing.title": "Personne ne m'a encore montré ça.", "learn.missing.ask": "Demander à un expert",
  "learn.notConfirmed": "Pas encore confirmé", "map.conflict": "Les experts divergent ici",
  "capture.offrecord": "Hors enregistrement", "debrief.publish": "Publier la carte",
  "map.filter.all": "Tout", "map.filter.judgment": "Jugements", "map.filter.guardrail": "Garde-fous", "map.filter.conflict": "Conflits", "map.filter.unconfirmed": "Non confirmé",
  "chip.judgment": "Jugement", "chip.guardrail": "Garde-fou", "chip.conflict": "Divergence", "chip.unconfirmed": "Non confirmé", "map.anyOrder": "Ordre libre", "map.open": "Ouvrir", "map.export": "Exporter", "map.learnThis": "Apprendre",
};

export const es: Dict = {
  "nav.home": "Inicio", "nav.learn": "Guíame", "nav.workflows": "Procesos", "nav.skip": "Ir al contenido", "nav.menu": "Menú", "nav.primary": "Principal",
  "role.label": "Viendo como", "role.learner": "Aprendiz", "role.expert": "Experto/a", "role.learner.sub": "Aprender en tu propia pantalla", "role.expert.sub": "Enseñar a Claros, responder dudas", "role.switch": "Cambiar rol",
  "lang.label": "Idioma", "theme.label": "Tema", "theme.system": "Sistema", "theme.light": "Claro", "theme.dark": "Oscuro",
  "crumb.home": "Inicio", "crumb.learn": "Guíame", "crumb.workflows": "Procesos", "focus.capture": "Grabación", "focus.debrief": "Repaso", "focus.exit": "Salir",
  "data.demo": "Datos demo", "data.demo.hint": "Servidor de Claros no disponible — datos demo",
  "common.open": "Abrir", "common.later": "Más tarde", "common.close": "Cerrar", "common.prev": "Paso anterior", "common.next": "Paso siguiente", "common.undo": "Deshacer", "common.all": "Todos",
  "cov.ready": "Listo", "cov.partial": "Parcial", "cov.missing": "Falta",
  "state.loading": "Cargando…", "state.error.title": "No se pudo cargar", "state.error.retry": "Reintentar",
  "home.expert.title": "Donde hace falta lo que sabes", "home.requests.title": "Solicitudes de aprendices", "req.record": "Grabar ahora", "req.later": "Más tarde",
  "home.questions.title": "Preguntas para ti", "q.answer": "Responder por voz", "home.workflows.title": "Tus procesos", "home.teach.title": "Enseñar algo nuevo a Claros", "home.teach.cta": "Empezar a grabar",
  "home.learner.title": "¿Atascado en una pantalla?", "home.learner.cta": "Guíame con esto", "home.continue.title": "Seguir aprendiendo", "home.library.title": "Procesos que puedes aprender", "home.myreq.title": "Tus solicitudes",
  "wf.learn": "Aprender", "wf.view": "Ver mapa",
  "learn.missing.title": "Nadie me ha enseñado esto todavía.", "learn.missing.ask": "Preguntar a un experto",
  "learn.notConfirmed": "Aún no confirmado", "map.conflict": "Los expertos difieren aquí",
  "capture.offrecord": "Fuera de registro", "debrief.publish": "Publicar mapa",
  "map.filter.all": "Todos", "map.filter.judgment": "Decisiones", "map.filter.guardrail": "Límites", "map.filter.conflict": "Conflictos", "map.filter.unconfirmed": "Sin confirmar",
  "chip.judgment": "Decisión", "chip.guardrail": "Límite", "chip.conflict": "Difieren", "chip.unconfirmed": "Sin confirmar", "map.anyOrder": "Cualquier orden", "map.open": "Abrir", "map.export": "Exportar", "map.learnThis": "Aprender",
};
